"""Guard against the migrations and the models drifting apart.

``tests/conftest.py`` builds its schema with ``Base.metadata.create_all`` because
that is fast. Production builds it by running the Alembic migration chain. Those
are two paths to the same schema and nothing stops them diverging -- someone
edits ``app/models.py``, the tests keep passing because create_all sees the new
model, and the missing migration is only discovered on deploy.

These tests close that gap. If ``test_migrations_match_models`` fails, the fix is
almost always:

    alembic revision --autogenerate -m "describe the change"

Requires PostgreSQL (see conftest). A separate database is used so the migration
chain never runs against the same schema the other tests are mutating.
"""

from __future__ import annotations

import os
import uuid
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext

from app.database import Base
import app.models  # noqa: F401  (populates Base.metadata)

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _alembic_config(url: str) -> Config:
    config = Config(str(PROJECT_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    config.set_main_option("sqlalchemy.url", url)
    return config


@pytest.fixture()
def migrated_url() -> str:
    """A scratch PostgreSQL database with the full migration chain applied.

    Created and dropped per test. CREATE DATABASE cannot run inside a
    transaction, hence the AUTOCOMMIT isolation level.
    """
    base_url = sa.engine.make_url(os.environ["DATABASE_URL"])
    scratch_name = f"cem_migrate_{uuid.uuid4().hex[:12]}"
    admin_url = base_url.set(database="postgres")

    admin = sa.create_engine(admin_url, isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as conn:
            conn.execute(sa.text(f'CREATE DATABASE "{scratch_name}"'))
    except sa.exc.OperationalError as exc:  # pragma: no cover
        pytest.skip(f"cannot create a scratch database: {exc}")

    scratch_url = base_url.set(database=scratch_name)
    try:
        command.upgrade(_alembic_config(str(scratch_url)), "head")
        yield str(scratch_url)
    finally:
        with admin.connect() as conn:
            conn.execute(
                sa.text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :name AND pid <> pg_backend_pid()"
                ),
                {"name": scratch_name},
            )
            conn.execute(sa.text(f'DROP DATABASE IF EXISTS "{scratch_name}"'))
        admin.dispose()


def test_migrations_match_models(migrated_url: str) -> None:
    """Running all migrations must produce exactly the schema the models describe."""
    engine = sa.create_engine(migrated_url)
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={"compare_type": True, "compare_server_default": True},
            )
            diff = compare_metadata(context, Base.metadata)
    finally:
        engine.dispose()

    assert diff == [], (
        "Migrations and models have drifted apart.\n"
        "Alembic found these differences after upgrading to head:\n"
        f"{diff}\n\n"
        "Fix with: alembic revision --autogenerate -m 'describe the change'"
    )


def test_migrations_are_reversible(migrated_url: str) -> None:
    """Every migration must roll back to an empty database and back up again.

    Catches the common case of an autogenerated ``downgrade()`` left as ``pass``,
    which makes a bad deploy unrecoverable without hand-written SQL.
    """
    config = _alembic_config(migrated_url)
    command.downgrade(config, "base")

    engine = sa.create_engine(migrated_url)
    try:
        with engine.connect() as connection:
            assert MigrationContext.configure(connection).get_current_revision() is None
    finally:
        engine.dispose()

    command.upgrade(config, "head")


def test_models_use_jsonb_not_json() -> None:
    """JSON columns must be JSONB.

    Plain JSON stores text and cannot be indexed or queried efficiently. The
    switch to JSONB was deliberate; this stops a future model gaining a plain
    JSON column by copy-paste.
    """
    plain_json = [
        f"{table.name}.{column.name}"
        for table in Base.metadata.sorted_tables
        for column in table.columns
        if isinstance(column.type, sa.JSON)
        and column.type.__class__.__name__ != "JSONB"
    ]
    assert plain_json == [], f"these columns use plain JSON, expected JSONB: {plain_json}"
