"""baseline postgres schema

Revision ID: 79ea7b4cc34e
Revises: 
Create Date: 2026-08-16 17:54:33.951157
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '79ea7b4cc34e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=220), nullable=False),
    sa.Column('common_name', sa.String(length=220), nullable=False),
    sa.Column('iucn_category', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_attribution', sa.Text(), nullable=True),
    sa.Column('migration_class', sa.String(length=40), nullable=True),
    sa.Column('activity_hours', sa.String(length=160), nullable=True),
    sa.Column('seasonality', sa.String(length=160), nullable=True),
    sa.Column('taxonomy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('network_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_index(op.f('ix_species_iucn_category'), 'species', ['iucn_category'], unique=False)
    op.create_index(op.f('ix_species_migration_class'), 'species', ['migration_class'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=True)
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_project_id', sa.String(length=120), nullable=False),
    sa.Column('source_spot_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', name='uq_spot_coordinates'),
    sa.UniqueConstraint('source_project_id', 'source_spot_id', name='uq_source_project_spot')
    )
    op.create_index(op.f('ix_spots_id'), 'spots', ['id'], unique=False)
    op.create_index(op.f('ix_spots_source_project_id'), 'spots', ['source_project_id'], unique=False)
    op.create_index(op.f('ix_spots_source_spot_id'), 'spots', ['source_spot_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(length=160), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('input_url', sa.Text(), nullable=True),
    sa.Column('output_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_analysis_jobs_analysis_type'), 'analysis_jobs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_species_id'), 'analysis_jobs', ['species_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_spot_id'), 'analysis_jobs', ['spot_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('spot_environment_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('sunrise_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('temperature_mean_c', sa.Float(), nullable=True),
    sa.Column('humidity_mean', sa.Float(), nullable=True),
    sa.Column('severe_weather', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'observation_date', name='uq_spot_environment_daily')
    )
    op.create_index(op.f('ix_spot_environment_daily_observation_date'), 'spot_environment_daily', ['observation_date'], unique=False)
    op.create_index(op.f('ix_spot_environment_daily_spot_id'), 'spot_environment_daily', ['spot_id'], unique=False)
    op.create_table('spot_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('source_project_id', sa.String(length=120), nullable=False),
    sa.Column('source_spot_id', sa.String(length=120), nullable=False),
    sa.Column('contributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_project_id', 'source_spot_id', name='uq_spot_source')
    )
    op.create_index(op.f('ix_spot_sources_source_project_id'), 'spot_sources', ['source_project_id'], unique=False)
    op.create_index(op.f('ix_spot_sources_source_spot_id'), 'spot_sources', ['source_spot_id'], unique=False)
    op.create_index(op.f('ix_spot_sources_spot_id'), 'spot_sources', ['spot_id'], unique=False)
    op.create_table('spot_species_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'species_id', 'observation_date', name='uq_spot_species_daily')
    )
    op.create_index('ix_species_date_spot', 'spot_species_daily', ['species_id', 'observation_date', 'spot_id'], unique=False)
    op.create_index(op.f('ix_spot_species_daily_observation_date'), 'spot_species_daily', ['observation_date'], unique=False)
    op.create_index(op.f('ix_spot_species_daily_species_id'), 'spot_species_daily', ['species_id'], unique=False)
    op.create_index(op.f('ix_spot_species_daily_spot_id'), 'spot_species_daily', ['spot_id'], unique=False)
    op.create_table('spot_species_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('activity_rank', sa.Integer(), nullable=True),
    sa.Column('migration_class', sa.String(length=40), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('maximum_confidence', sa.Float(), nullable=True),
    sa.Column('first_detection_date', sa.Date(), nullable=True),
    sa.Column('last_detection_date', sa.Date(), nullable=True),
    sa.Column('activity_regularity', sa.Float(), nullable=True),
    sa.Column('hourly_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'species_id', name='uq_spot_species_summary')
    )
    op.create_index('ix_species_spot_activity', 'spot_species_summaries', ['species_id', 'detection_count'], unique=False)
    op.create_index('ix_spot_species_activity', 'spot_species_summaries', ['spot_id', 'detection_count'], unique=False)
    op.create_index(op.f('ix_spot_species_summaries_migration_class'), 'spot_species_summaries', ['migration_class'], unique=False)
    op.create_index(op.f('ix_spot_species_summaries_species_id'), 'spot_species_summaries', ['species_id'], unique=False)
    op.create_index(op.f('ix_spot_species_summaries_spot_id'), 'spot_species_summaries', ['spot_id'], unique=False)
    op.create_table('spot_summaries',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('recording_count', sa.Integer(), nullable=False),
    sa.Column('species_richness', sa.Integer(), nullable=False),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('first_recording_date', sa.Date(), nullable=True),
    sa.Column('last_recording_date', sa.Date(), nullable=True),
    sa.Column('acoustic_indices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_summaries')
    op.drop_index(op.f('ix_spot_species_summaries_spot_id'), table_name='spot_species_summaries')
    op.drop_index(op.f('ix_spot_species_summaries_species_id'), table_name='spot_species_summaries')
    op.drop_index(op.f('ix_spot_species_summaries_migration_class'), table_name='spot_species_summaries')
    op.drop_index('ix_spot_species_activity', table_name='spot_species_summaries')
    op.drop_index('ix_species_spot_activity', table_name='spot_species_summaries')
    op.drop_table('spot_species_summaries')
    op.drop_index(op.f('ix_spot_species_daily_spot_id'), table_name='spot_species_daily')
    op.drop_index(op.f('ix_spot_species_daily_species_id'), table_name='spot_species_daily')
    op.drop_index(op.f('ix_spot_species_daily_observation_date'), table_name='spot_species_daily')
    op.drop_index('ix_species_date_spot', table_name='spot_species_daily')
    op.drop_table('spot_species_daily')
    op.drop_index(op.f('ix_spot_sources_spot_id'), table_name='spot_sources')
    op.drop_index(op.f('ix_spot_sources_source_spot_id'), table_name='spot_sources')
    op.drop_index(op.f('ix_spot_sources_source_project_id'), table_name='spot_sources')
    op.drop_table('spot_sources')
    op.drop_index(op.f('ix_spot_environment_daily_spot_id'), table_name='spot_environment_daily')
    op.drop_index(op.f('ix_spot_environment_daily_observation_date'), table_name='spot_environment_daily')
    op.drop_table('spot_environment_daily')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_spot_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_species_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_analysis_type'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_spots_source_spot_id'), table_name='spots')
    op.drop_index(op.f('ix_spots_source_project_id'), table_name='spots')
    op.drop_index(op.f('ix_spots_id'), table_name='spots')
    op.drop_table('spots')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_migration_class'), table_name='species')
    op.drop_index(op.f('ix_species_iucn_category'), table_name='species')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
